apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  labels:
    app: member
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      name: member
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: wan2da/havday-server-member-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http-web-svc
      restartPolicy: Always

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: member-service  # 서비스 이름
#spec:
#  selector: # 셀렉터 설정
#    app: member
#  type: NodePort
#  ports:              # 포트 설정
#    - protocol: TCP      # 서비스 포트
#      port: 8080
#      targetPort: 8080 # 파드 포트
#      nodePort: 30081 # 워커 노드의 포트 (30000 ~ 32767) localhost:30081 <- 이렇게 접근 가능
#
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: member
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc