spring.application.name: api-gateway


jwt:
  secret-key: asldkasjldkajsldkjalskdjalskdjasd


spring:
  main:
    web-application-type: reactive
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: test