name: havday service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: build docker image files and push to docker hub with Makefile
      env:
          REPOSITORY: wan2da
      run: |
        make REPOSITORY=$REPOSITORY